title: EmbeddedHunter
description: Code repository of Embedded Bandits for Large-Scale Black-Box Optimization (AAAI'17)
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
